# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a7661054d36e22b0d888e1a5b9422c50a6b09a433db86b5df733a5768cafe027b4835b788a194bcf073a92b07e16b605546968146dccc58d1abed9097b02091

test:
  secret_key_base: a6ef51d2f796ac62833a5b8e5abce261e8ee7ef07610754a533b0459171252917f2607ad53ed3c0a6f1f6ab9f88897371217fda4e35edc171be59dce621acf02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
